version: "3"

services:
  web:
    build: ./php/docker/
    ports:
      - 81:80
    volumes:
      - "./php/file/:/var/www/html/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true
    stdin_open: true
    depends_on:
      - python
      - mysql
    links:
      - python
      - mysql

  python:
    build: ./python/docker/
    volumes:
      - "./python/file/:/work/"
      - "./php/file/audio/:/work/audio/"
      - "./python/file/cache/nvidia_DeepLearningExamples_torchhub/:/root/.cache/torch/hub/nvidia_DeepLearningExamples_torchhub/"
      - "./python/file/cache/NVIDIA_DeepLearningExamples_torchhub/:/root/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/"
        #runtime: nvidia
        #environment:
        #- NVIDIA_VISIBLE_DEVICES=all
    tty: true
    stdin_open: true

  mysql:
    image: mysql:5.6
      #image: mysql:8.0.20
    volumes:
      - ./db/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lesson
      MYSQL_DATABASE: lesson
      MYSQL_USER: lesson
      MYSQL_PASSWORD: lesson
        #MYSQL_TCP_PORT: 3306
